version: "3.4"

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    env_file: 
      - ./front/.env
    restart: always
    stdin_open: true
    tty: true
    ports:
      - ${VITE_PORT:-5173}:${VITE_PORT:-5173}
    volumes:
      - ./front:/usr/src/app
    command: npm run dev
