controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

authentication_token:
    path: /authentication_token
    methods: ["POST"]

refresh_token:
    path: /token/refresh
